FROM node:20-alpine
WORKDIR /app

ENV CHOKIDAR_USEPOLLING=true
ENV CHOKIDAR_INTERVAL=300
ENV WATCHPACK_POLLING=true

COPY package*.json ./
RUN npm ci

COPY . .

EXPOSE 5173
CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0", "--port", "5173"]
